### ISSUE TITLE
weighted pp change sometimes has +- in front of it instead of just +

### ISSUE THREAD

**Issue by PatTheHyruler** [Kiyomi-Parents/Kiyomi#12]
![Screenshot_2021-07-20-19-34-00-643_com.discord.jpg](https://user-images.githubusercontent.com/55945965/126362044-38d4a1bc-4a1e-4017-83e3-2e564c13e814.jpg)

**Comment by PatTheHyruler** [comment]
also wait what the actual value of the change is strange as well

**Comment by PatTheHyruler** [comment]
another example![Screenshot_2021-07-20-19-41-13-262_com.discord.jpg](https://user-images.githubusercontent.com/55945965/126362824-776ab804-0d7b-4aa1-a807-062e39a2a6ed.jpg)

**Comment by PatTheHyruler** [comment]
Finally took a look at this.
I assume that this happens because the pp weight of the new score isn't the same it would've been, had it been set at the time as the old score. So, in order to make them compatible, we would need to get the new pp weight of the older score.

HOWEVER, since as far as I can tell, the ScoreSaber API doesn't currently let you find a specific score by scoreId, we'd need to look at the player's top scores to calculate it on our own.
I suppose we could go through the player's top scores page by page on ScoreSaber, but since @LuCkEr- wanted to get the bot to download all the scores of every registered player anyway, maybe we can do something with that instead?

**Comment by LuCkEr-** [comment]
Fixed at refactor
