### ISSUE TITLE
Should maybe remove the pp field from non-ranked scores

### ISSUE THREAD

**Issue by PatTheHyruler** [Kiyomi-Parents/Kiyomi#13]

**Comment by LuCkEr-** [comment]
yeah, you can add a new property in https://github.com/PatTheHyruler/BSBot/blob/79c2a4158d0d11777f41adc9e2ae7cbc78285b60/src/cogs/beatsaber/storage/model/score.py#L16 which returns a boolean on whether the score is ranked or not. I think you can just check if the
https://github.com/PatTheHyruler/BSBot/blob/79c2a4158d0d11777f41adc9e2ae7cbc78285b60/src/cogs/beatsaber/storage/model/score.py#L29 is set to None in the property function. After that we can use the new property function to check if the score was ranked in the message embeds and act accordingly

**Comment by LuCkEr-** [comment]
Fixed
