### ISSUE TITLE
Move Discord token into a json config file

### ISSUE THREAD

**Issue by LuCkEr-** [Kiyomi-Parents/Kiyomi#21]
``It's a bit annoying to have to export the Discord token every time.
Make sure to also include the config.json file in .gitignore

The config can look something like this:
`
{
"discord_token": "<YOUR DISCORD TOKEN HERE>"
}
`

**Comment by alvaroartano** [comment]
I have done it! #36

**Comment by alvaroartano** [comment]
@LuCkEr-

**Comment by LuCkEr-** [comment]
Sorry for the wait. We aren't working on the master branch currently. Would be awesome if you could send a pull request for the refactor branch. There are also some additional variables that need to be read from the config over at https://github.com/Kiyomi-Parents/Kiyomi/blob/f16f2a6080a2475e9ce14704941ff56387469e48/Kiyomi.py#L11.
