### ISSUE TITLE
Bot hasn't fetched recent score after 3 hours

### ISSUE THREAD

**Issue by PatTheHyruler** [Kiyomi-Parents/Kiyomi#22]
![image](https://user-images.githubusercontent.com/55945965/129607392-f033c33f-d740-44d1-8364-f09e4ab65dfb.png)
![image](https://user-images.githubusercontent.com/55945965/129607546-a00e5bab-f280-4a8a-8655-2c28104cb5c8.png)

**Comment by PatTheHyruler** [comment]
My scores still aren't being updated:
![image](https://user-images.githubusercontent.com/55945965/129992684-06bda02e-3ca1-4dd9-af59-f127a160c8a6.png)
![image](https://user-images.githubusercontent.com/55945965/129992664-d794a986-2971-4ae1-b44e-b0fc67e51186.png)
Seems to be working for other people tho.

**Comment by LuCkEr-** [comment]
Confrim if fixed, feel free to close this after.
