### ISSUE TITLE
Score feed shows modifiers that shouldn't be there

### ISSUE THREAD

**Issue by PatTheHyruler** [Kiyomi-Parents/Kiyomi#23]
![image](https://user-images.githubusercontent.com/55945965/129607626-890bb19b-e18a-4834-bf93-8a12bf7312cf.png)
![image](https://user-images.githubusercontent.com/55945965/129608056-72f19587-d00b-4a64-a0f5-af66fde01fa2.png)

**Comment by LuCkEr-** [comment]
Score Saber api is showing modifiers. So probably Score Sabers fault.
![](https://share.lucker.xyz/qahu5/CirAwosi26.png/raw)

**Comment by PatTheHyruler** [comment]
yeah scoresaber
