### ISSUE TITLE
Better score modifier representation in embeds

### ISSUE THREAD

**Issue by LuCkEr-** [Kiyomi-Parents/Kiyomi#25]
The idea is to use the beat saber score modifier icons from ingame inside the embed.
![](https://share.lucker.xyz/qahu5/ZeNOVOVa31.png/raw)
![](https://share.lucker.xyz/qahu5/cuVEgitu01.png/raw)

**Comment by PatTheHyruler** [comment]
Modifiers list with corresponding ScoreSaber modifiers

No Fail - NF
1 Life - IF
4 Lives - BE
No Bombs - NB
No Walls - NO
No Arrows - NA
Ghost Notes - GN
Disappearing Arrows - DA
Small Notes - SC
Pro Mode - PM
Strict Angles - SA
Zen Mode - [doesn't submit?]
Slower Song - SS
Faster Song - FS
Super Fast Song - SF

**Comment by LuCkEr-** [comment]
Can also get icons for difficulties

**Comment by LuCkEr-** [comment]
Actually done
