### ISSUE TITLE
Discord leaderboard Score date is off by a few hours

### ISSUE THREAD

**Issue by PatTheHyruler** [Kiyomi-Parents/Kiyomi#39]
![image](https://user-images.githubusercontent.com/55945965/137640514-8b013809-6404-49b1-a2ac-7408b4a9079a.png)
![image](https://user-images.githubusercontent.com/55945965/137640525-93b1df15-bf27-4619-9232-331e060cbc57.png)
Probably a timezone thing.

**Comment by LuCkEr-** [comment]
Maybe fixed with #59
