### ISSUE TITLE
PP roles feature is still broken

### ISSUE THREAD

**Issue by PatTheHyruler** [Kiyomi-Parents/Kiyomi#50]
Roles don't seem to update when people pass a PP milestone.
Also, we should probably make sure that when people lose PP and fall below a milestone, their roles get updated accordingly.

**Comment by LuCkEr-** [comment]
There's also a problem with the server admins messing around with the bot generated roles, which breaks the bot atm.

**Comment by LuCkEr-** [comment]
Actually fixed
