### ISSUE TITLE
!update commands get logged twice?

### ISSUE THREAD

**Issue by PatTheHyruler** [Kiyomi-Parents/Kiyomi#9]
![image](https://user-images.githubusercontent.com/55945965/122651536-37d9cf00-d142-11eb-8bb1-0ccc21fe2aea.png)

**Comment by LuCkEr-** [comment]
I've noticed that some commands seem to get logged twice also but i haven't investigated that yet.

**Comment by LuCkEr-** [comment]
This probably got fixed somewhere, havent seen this happen for a while
